// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_bAQaefvp2C4-qO80Wjp5JlDt6nAU8M',
    appId: '1:970217973487:android:02c4d213dbf34fe71d1d1a',
    messagingSenderId: '970217973487',
    projectId: 'little-miracles-app',
    storageBucket: 'little-miracles-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY_bAQaefvp2C4-qO80Wjp5JlDt6nAU8M',
    appId: '1:970217973487:ios:935a943dec36d6ea1d1d1a',
    messagingSenderId: '970217973487',
    projectId: 'little-miracles-app',
    storageBucket: 'little-miracles-app.appspot.com',
    iosClientId:
        '970217973487-tp7i2ihrugrnch743vfdg3u1fum423u4.apps.googleusercontent.com',
    iosBundleId: 'com.littlemiracles',
  );
}
